// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/3/2025, 10:37:25 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/profile/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/profile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/profile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/profile/plugins/**/*.{js,ts,mjs}","D:/profile/composables/**/*.{js,ts,mjs}","D:/profile/utils/**/*.{js,ts,mjs}","D:/profile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/profile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/profile/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;